dist: xenial
language: python
cache: pip
python:
    - "3.5"
addons:
    apt:
        packages:
            - python3-pip
            - python3-dev
            - debhelper
            - devscripts
            - debhelper
            - devscripts
            - p7zip-full
            - libssl-dev
            - dpkg-dev
            - build-essential
            - libjpeg-dev
            - libtiff-dev
            - libsdl1.2-dev
            - libnotify-dev
            - freeglut3
            - ibus-gtk3
            - xvfb
            - libhunspell-dev
            - gstreamer1.0-pulseaudio
            - gstreamer0.10-alsa
            - libwebkit2gtk-4.0
install:
    - python -m pip install pipenv
    - pipenv run pip install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython==4.0.6
    - pipenv update --dev
script:
    - xvfb-run pipenv run fab test
